create table `index_snapshot` (
    `id` int(10) not null auto_increment,
    `index_id` tinyint(3) not null,
    `open` float(10, 2) not null default 0.0,
    `high` float(10, 2) not null default 0.0,
    `low` float(10, 2) not null default 0.0,
    `close` float(10, 2) not null default 0.0,
    `date` date not null,
    primary key (`id`),
    index (`index_id`)
);

insert into `indexes` (`name`, `created_at`, `updated_at`)
    values ('Nifty Next 50', NOW(), NOW());
    
insert into `companies` (`name`, `symbol`, `created_at`, `updated_at`)
    values ('ABB India Ltd.', 'ABB', NOW(), NOW()),
        ('ACC Ltd.', 'ACC', NOW(), NOW()),
        ('Aditya Birla Capital Ltd.', 'ABCAPITAL', NOW(), NOW()),
        ('Ambuja Cements Ltd.', 'AMBUJACEM', NOW(), NOW()),
        ('Ashok Leyland Ltd.', 'ASHOKLEY', NOW(), NOW()),
        ('Aurobindo Pharma Ltd.', 'AUROPHARMA', NOW(), NOW()),
        ('Avenue Supermarts Ltd.', 'DMART', NOW(), NOW()),
        ('Bandhan Bank Ltd.', 'BANDHANBNK', NOW(), NOW()),
        ('Bank of Baroda', 'BANKBARODA', NOW(), NOW()),
        ('Bharat Electronics Ltd.', 'BEL', NOW(), NOW()),
        ("Bharat Heavy Electricals Ltd.", 'BHEL', NOW(), NOW()),
        ('Biocon Ltd.', 'BIOCON', NOW(), NOW()),
        ('Bosch Ltd.', 'BOSCHLTD', NOW(), NOW()),
        ('Britannia Industries Ltd.', 'BRITANNIA', NOW(), NOW()),
        ('Cadila Healthcare Ltd.', 'CADILAHC', NOW(), NOW()),
        ('Colgate Palmolive (India) Ltd.', 'COLPAL', NOW(), NOW()),
        ('Container Corporation of India Ltd.', 'CONCOR', NOW(), NOW()),
        ('DLF Ltd.', 'DLF', NOW(), NOW()),
        ('Dabur India Ltd.', 'DABUR', NOW(), NOW()),
        ('General Insurance Corporation of India', 'GICRE', NOW(), NOW()),
        ('Godrej Consumer Products Ltd.', 'GODREJCP', NOW(), NOW()),
        ('HDFC Standard Life Insurance Company Ltd.', 'HDFCLIFE', NOW(), NOW()),
        ('Havells India Ltd.', 'HAVELLS', NOW(), NOW()),
        ('Hindustan Zinc Ltd.', 'HINDZINC', NOW(), NOW()),
        ('ICICI Lombard General Insurance Company Ltd.', 'ICICIGI', NOW(), NOW()),
        ('ICICI Prudential Life Insurance Company Ltd.', 'ICICIPRULI', NOW(), NOW()),
        ('InterGlobe Aviation Ltd.', 'INDIGO', NOW(), NOW()),
        ('L&T Finance Holdings Ltd.', 'L&TFH', NOW(), NOW()),
        ('LIC Housing Finance Ltd.', 'LICHSGFIN', NOW(), NOW()),
        ('JSW Steel Ltd.', 'JSWSTEEL', NOW(), NOW()),
        ('MRF Ltd.', 'MRF', NOW(), NOW()),
        ('Marico Ltd.', 'MARICO', NOW(), NOW()),
        ('Motherson Sumi Systems Ltd.', 'MOTHERSUMI', NOW(), NOW()),
        ('NHPC Ltd.', 'NHPC', NOW(), NOW()),
        ('NMDC Ltd.', 'NMDC', NOW(), NOW()),
        ('Oil India Ltd.', 'OIL', NOW(), NOW()),
        ('Oracle Financial Services Software Ltd.', 'OFSS', NOW(), NOW()),
        ('Petronet LNG Ltd.', 'PETRONET', NOW(), NOW()),
        ('Pidilite Industries Ltd.', 'PIDILITIND', NOW(), NOW()),
        ('Piramal Enterprises Ltd.', 'PEL', NOW(), NOW()),
        ('Procter & Gamble Hygiene & Health Care Ltd.', 'PGHH', NOW(), NOW()),
        ('SBI Life Insurance Company Ltd.', 'SBILIFE', NOW(), NOW()),
        ('Shree Cement Ltd.', 'SHREECEM', NOW(), NOW()),
        ('Shriram Transport Finance Co. Ltd.', 'SRTRANSFIN', NOW(), NOW()),
        ('Siemens Ltd.', 'SIEMENS', NOW(), NOW()),
        ('Steel Authority of India Ltd.', 'SAIL', NOW(), NOW()),
        ('Sun TV Network Ltd.', 'SUNTV', NOW(), NOW()),
        ('The New India Assurance Company Ltd.', 'NIACL', NOW(), NOW()),
        ('United Spirits Ltd.', 'MCDOWELL-N', NOW(), NOW()),
        ('Vodafone Idea Ltd.', 'IDEA', NOW(), NOW());
        
insert into `index_companies` (`index_id`, `company_id`, `status`, `created_at`, `updated_at`)
    values (1, (select id from companies where symbol = 'JSWSTEEL'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'ABB'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'ACC'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'ABCAPITAL'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'AMBUJACEM'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'ASHOKLEY'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'AUROPHARMA'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'DMART'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'BANDHANBNK'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'BANKBARODA'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'BEL'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'BHEL'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'BIOCON'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'BOSCHLTD'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'BRITANNIA'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'CADILAHC'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'COLPAL'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'CONCOR'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'DLF'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'DABUR'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'GICRE'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'GODREJCP'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'HDFCLIFE'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'HAVELLS'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'HINDZINC'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'ICICIGI'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'ICICIPRULI'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'INDIGO'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'L&TFH'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'LICHSGFIN'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'MRF'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'MARICO'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'MOTHERSUMI'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'NHPC'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'NMDC'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'OIL'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'OFSS'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'PETRONET'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'PIDILITIND'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'PEL'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'PGHH'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'SBILIFE'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'SHREECEM'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'SRTRANSFIN'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'SIEMENS'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'SAIL'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'SUNTV'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'NIACL'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'MCDOWELL-N'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'IDEA'), 1, NOW(), NOW()),
        (2, (select id from companies where symbol = 'LUPIN'), 1, NOW(), NOW());